version: '3'

services:
  currecnies-service:
    container_name: currecnies-service
    build: .
    ports:
      - ${PORT}:${PORT}
    command: npm run start
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4.2.6
    networks:
      - webnet
    volumes:
      - mongodb:/data/db
    command: mongod
networks:
  webnet:
volumes:
  mongodb:
